"""remove test column

Revision ID: 07182c34a3e5
Revises: c4e2a5995b9c
Create Date: 2021-06-21 14:01:44.452718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07182c34a3e5'
down_revision = 'c4e2a5995b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'test_column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('test_column', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
