"""add user verification

Revision ID: 7146644d2c10
Revises: 0e6dc5924477
Create Date: 2021-07-01 12:21:46.735203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7146644d2c10'
down_revision = '0e6dc5924477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isVerified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', 'isVerified')
    # ### end Alembic commands ###
